// packages/solid/src/components/Auth/Auth.tsx
import { createStitches, createTheme } from '@stitches/core'
import merge from 'just-merge'
import {
  I18nVariables,
  SocialLayouts,
  VIEWS,
  en,
  it,
  SocialLayout,
  OtpType,
  ViewType,
} from '@supabase/auth-ui-shared'
import { Auth as AuthProps } from '../../types'
import {
  EmailAuth,
  EmailAuthProps,
  ForgottenPassword,
  MagicLink,
  SocialAuth,
  UpdatePassword,
  VerifyOtp,
} from './interfaces'
import { UserContextProvider, useUser } from './UserContext'

import {
  Accessor,
  createEffect,
  createMemo,
  createSignal,
  JSX,
  JSXElement,
  Match,
  mergeProps,
  onCleanup,
  onMount,
  Show,
  Switch,
} from 'solid-js'
import { createStore } from 'solid-js/store'

function Auth(props: AuthProps): JSX.Element | null {
  /**
   * Localization support
   */

  const mergedProps = createMemo(() => {
    const merged = mergeProps(
      {
        socialLayout: SocialLayouts.horizontal,
        view: 'sign_in' as ViewType,
        onlyThirdPartyProviders: false,
        magicLink: false,
        showLinks: true,
        theme: 'default',
        localization: { variables: {} },
        otpType: 'email',
        passwordLimit: false,
      },
      props
    )
    return merged
  })

  const i18n: Accessor<I18nVariables> = createMemo(() => {
    let language = en
    if (props.localization?.language === 'it') language = it
    const merged = merge(
      //@ts-ignore
      language,
      mergedProps().localization.variables ?? {}
    )
    return merged
  })

  const [authView, setAuthView] = createSignal(mergedProps().view)
  const [defaultEmail, setDefaultEmail] = createSignal('')
  const [defaultPassword, setDefaultPassword] = createSignal('')
  const [themes, setThemes] = createSignal({})

  /**
   * Simple boolean to detect if authView 'sign_in' or 'sign_up' is used
   *
   * @returns boolean
   */
  const [SignView, setSignView] = createSignal()

  onMount(() => {
    setSignView(
      authView() === 'sign_in' ||
        authView() === 'sign_up' ||
        authView() === 'magic_link'
    )
  })

  createEffect(() => {
    /**
     * Create default theme
     *
     * createStitches()
     * https://stitches.dev/docs/api#theme
     *
     * to add a new theme use  createTheme({})
     * https://stitches.dev/docs/api#theme
     */
    setSignView(
      authView() === 'sign_in' ||
        authView() === 'sign_up' ||
        authView() === 'magic_link'
    )
    createStitches({
      theme: merge(
        mergedProps().appearance?.theme?.default ?? {},
        mergedProps().appearance?.variables?.default ?? {}
      ),
    })

    const themes: any = {}
    const themeKeys =
      mergedProps().appearance?.theme &&
      //@ts-ignore
      Object.keys(mergedProps().appearance?.theme)

    if (themeKeys) {
      mergedProps().appearance?.theme &&
        //@ts-ignore
        Object.values(mergedProps().appearance?.theme).map((theme, i) => {
          const key = themeKeys[i]
          // ignore default theme
          if (key === 'default') return {}

          const merged = merge(
            (mergedProps().appearance &&
              mergedProps().appearance?.theme &&
              mergedProps().appearance?.theme?.[key]) ??
              {},
            (mergedProps().appearance &&
              mergedProps().appearance?.variables &&
              mergedProps().appearance?.variables?.[key]) ??
              {}
          )

          themes[themeKeys[i]] = merged
        })
    }

    setThemes(themes)
  })

  /**
   * Wraps around all auth components
   * renders the social auth providers if SignView is true
   *
   * also handles the theme override
   *
   */
  const Container = (props: { children: JSXElement }) => (
    <div
      class={
        mergedProps().theme !== 'default'
          ? createTheme(
              merge(
                // @ts-ignore
                mergedProps().appearance?.theme[mergedProps().theme],
                mergedProps().appearance?.variables?.[mergedProps().theme] ?? {}
              )
            )
          : ''
      }
    >
      <Show when={SignView()}>
        <SocialAuth
          appearance={mergedProps().appearance}
          supabaseClient={mergedProps().supabaseClient}
          providers={mergedProps().providers}
          providerScopes={mergedProps().providerScopes}
          queryParams={mergedProps().queryParams}
          socialLayout={mergedProps().socialLayout as SocialLayout}
          redirectTo={mergedProps().redirectTo}
          onlyThirdPartyProviders={mergedProps().onlyThirdPartyProviders}
          i18n={i18n()}
          view={authView() as 'sign_in' | 'sign_up' | 'magic_link'}
        />
      </Show>

      <Show when={!mergedProps().onlyThirdPartyProviders}>
        {props.children}
      </Show>
    </div>
  )

  createEffect(() => {
    /**
     * Overrides the authview if it is changed externally
     */
    const { data: authListener } =
      mergedProps().supabaseClient.auth.onAuthStateChange((event, session) => {
        if (event === 'PASSWORD_RECOVERY') {
          setAuthView(VIEWS.UPDATE_PASSWORD)
        } else if (event === 'USER_UPDATED') {
          setAuthView(VIEWS.SIGN_IN)
        }
      })
    setAuthView(mergedProps().view)

    onCleanup(() => authListener.subscription.unsubscribe())
  })

  const [emailProp, setEmailProp] = createStore<
    Omit<EmailAuthProps, 'authView' | 'id'>
  >({
    supabaseClient: mergedProps().supabaseClient,
    setAuthView,
    defaultEmail: defaultEmail(),
    defaultPassword: defaultPassword(),
    setDefaultEmail,
    setDefaultPassword,
    redirectTo: mergedProps().redirectTo,
    magicLink: mergedProps().magicLink,
    showLinks: mergedProps().showLinks,
    i18n: i18n(),
    passwordLimit: mergedProps().passwordLimit,
  })

  /**
   * View handler, displays the correct Auth view
   * all views are wrapped in <Container/>
   */
  return (
    <Switch fallback={null}>
      <Match when={authView() === VIEWS.SIGN_IN}>
        <Container>
          <EmailAuth
            {...emailProp}
            authView={'sign_in'}
            appearance={mergedProps().appearance}
          />
        </Container>
      </Match>

      <Match when={authView() === VIEWS.SIGN_UP}>
        <Container>
          <EmailAuth
            appearance={mergedProps().appearance}
            supabaseClient={mergedProps().supabaseClient}
            authView={'sign_up'}
            setAuthView={setAuthView}
            defaultEmail={defaultEmail()}
            defaultPassword={defaultPassword()}
            setDefaultEmail={setDefaultEmail}
            setDefaultPassword={setDefaultPassword}
            redirectTo={mergedProps().redirectTo}
            magicLink={mergedProps().magicLink}
            showLinks={mergedProps().showLinks}
            i18n={i18n()}
            passwordLimit={mergedProps().passwordLimit}
            additionalData={mergedProps().additionalData}
          >
            {props.children}
          </EmailAuth>
        </Container>
      </Match>

      <Match when={authView() === VIEWS.FORGOTTEN_PASSWORD}>
        <ForgottenPassword
          appearance={mergedProps().appearance}
          supabaseClient={mergedProps().supabaseClient}
          setAuthView={setAuthView}
          redirectTo={mergedProps().redirectTo}
          showLinks={mergedProps().showLinks}
          i18n={i18n()}
        />
      </Match>

      <Match when={authView() === VIEWS.MAGIC_LINK}>
        <Container>
          <MagicLink
            appearance={mergedProps().appearance}
            supabaseClient={mergedProps().supabaseClient}
            setAuthView={setAuthView}
            redirectTo={mergedProps().redirectTo}
            showLinks={mergedProps().showLinks}
            i18n={i18n()}
          />
        </Container>
      </Match>

      <Match when={authView() === VIEWS.UPDATE_PASSWORD}>
        <UpdatePassword
          appearance={mergedProps().appearance}
          supabaseClient={mergedProps().supabaseClient}
          passwordLimit={mergedProps().passwordLimit}
          i18n={i18n()}
        />
      </Match>

      <Match when={authView() === VIEWS.VERIFY_OTP}>
        <VerifyOtp
          appearance={mergedProps().appearance}
          supabaseClient={mergedProps().supabaseClient}
          setAuthView={setAuthView}
          otpType={mergedProps().otpType as OtpType}
          i18n={i18n()}
        />
      </Match>
    </Switch>
  )
}

Auth.ForgottenPassword = ForgottenPassword
Auth.UpdatePassword = UpdatePassword
Auth.MagicLink = MagicLink
Auth.UserContextProvider = UserContextProvider
Auth.useUser = useUser

export default Auth

// packages/react/src/components/Auth/Auth.tsx
import { createStitches, createTheme } from '@stitches/core'
import { I18nVariables, merge, VIEWS, en, it } from '@supabase/auth-ui-shared'
import React, { useEffect, useState } from 'react'
import { Auth as AuthProps } from '../../types'
import {
  EmailAuth,
  EmailAuthProps,
  ForgottenPassword,
  MagicLink,
  SocialAuth,
  UpdatePassword,
  VerifyOtp,
} from './interfaces'
import { UserContextProvider, useUser } from './UserContext'

function Auth({
  supabaseClient,
  socialLayout = 'vertical',
  providers,
  providerScopes,
  queryParams,
  view = 'sign_in',
  redirectTo,
  onlyThirdPartyProviders = false,
  magicLink = false,
  showLinks = true,
  appearance,
  theme = 'default',
  localization = { variables: {} }, // default language is english
  otpType = 'email',
  additionalData,
  passwordLimit,
  children,
}: AuthProps): JSX.Element | null {
  /**
   * Localization support
   */

  let language = en
  if(localization.language === 'it') language = it 
  const i18n: I18nVariables = merge(language, localization.variables ?? {})
  const [authView, setAuthView] = useState(view)
  const [defaultEmail, setDefaultEmail] = useState('')
  const [defaultPassword, setDefaultPassword] = useState('')

  /**
   * Simple boolean to detect if authView 'sign_in' or 'sign_up' or 'magic_link' is used
   *
   * @returns boolean
   */
  const SignView =
    authView === 'sign_in' ||
    authView === 'sign_up' ||
    authView === 'magic_link'

  useEffect(() => {
    createStitches({
      theme: merge(
        appearance?.theme?.default ?? {},
        appearance?.variables?.default ?? {}
      ),
    })
  }, [appearance])

  /**
   * Wraps around all auth components
   * renders the social auth providers if SignView is true
   *
   * also handles the theme override
   *
   * @param children
   * @returns React.ReactNode
   */
  const Container = ({ children }: { children: React.ReactNode }) => (
    // @ts-ignore
    <div
      className={
        theme !== 'default'
          ? createTheme(
              merge(
                // @ts-ignore
                appearance?.theme[theme],
                appearance?.variables?.[theme] ?? {}
              )
            )
          : ''
      }
    >
      {SignView && (
        <SocialAuth
          appearance={appearance}
          supabaseClient={supabaseClient}
          providers={providers}
          providerScopes={providerScopes}
          queryParams={queryParams}
          socialLayout={socialLayout}
          redirectTo={redirectTo}
          onlyThirdPartyProviders={onlyThirdPartyProviders}
          i18n={i18n}
          view={authView}
        />
      )}
      {!onlyThirdPartyProviders && children}
    </div>
  )

  useEffect(() => {
    /**
     * Overrides the authview if it is changed externally
     */
    const { data: authListener } = supabaseClient.auth.onAuthStateChange(
      (event) => {
        if (event === 'PASSWORD_RECOVERY') {
          setAuthView('update_password')
        } else if (event === 'USER_UPDATED') {
          setAuthView('sign_in')
        }
      }
    )
    setAuthView(view)

    return () => authListener.subscription.unsubscribe()
  }, [view])

  const emailProp: Omit<EmailAuthProps, 'authView' | 'id'> = {
    supabaseClient,
    setAuthView,
    defaultEmail,
    defaultPassword,
    setDefaultEmail,
    setDefaultPassword,
    redirectTo,
    magicLink,
    showLinks,
    i18n,
    appearance,
    passwordLimit,
  }

  /**
   * View handler, displays the correct Auth view
   * all views are wrapped in <Container/>
   */
  switch (authView) {
    case VIEWS.SIGN_IN:
      return (
        <Container>
          <EmailAuth {...emailProp} authView={'sign_in'} />
        </Container>
      )
    case VIEWS.SIGN_UP:
      return (
        <Container>
          <EmailAuth
            appearance={appearance}
            supabaseClient={supabaseClient}
            authView={'sign_up'}
            setAuthView={setAuthView}
            defaultEmail={defaultEmail}
            defaultPassword={defaultPassword}
            setDefaultEmail={setDefaultEmail}
            setDefaultPassword={setDefaultPassword}
            redirectTo={redirectTo}
            magicLink={magicLink}
            showLinks={showLinks}
            i18n={i18n}
            additionalData={additionalData}
            passwordLimit={passwordLimit}
            children={children}
          />
        </Container>
      )
    case VIEWS.FORGOTTEN_PASSWORD:
      return (
        <Container>
          <ForgottenPassword
            appearance={appearance}
            supabaseClient={supabaseClient}
            setAuthView={setAuthView}
            redirectTo={redirectTo}
            showLinks={showLinks}
            i18n={i18n}
          />
        </Container>
      )

    case VIEWS.MAGIC_LINK:
      return (
        <Container>
          <MagicLink
            appearance={appearance}
            supabaseClient={supabaseClient}
            setAuthView={setAuthView}
            redirectTo={redirectTo}
            showLinks={showLinks}
            i18n={i18n}
          />
        </Container>
      )

    case VIEWS.UPDATE_PASSWORD:
      return (
        <UpdatePassword
          appearance={appearance}
          supabaseClient={supabaseClient}
          i18n={i18n}
          passwordLimit={passwordLimit}
        />
      )
    case VIEWS.VERIFY_OTP:
      return (
        <VerifyOtp
          appearance={appearance}
          supabaseClient={supabaseClient}
          otpType={otpType}
          i18n={i18n}
        />
      )
    default:
      return null
  }
}

// @ts-ignore
Auth.ForgottenPassword = ForgottenPassword
// @ts-ignore
Auth.UpdatePassword = UpdatePassword
// @ts-ignore
Auth.MagicLink = MagicLink
// @ts-ignore
Auth.UserContextProvider = UserContextProvider
// @ts-ignore
Auth.useUser = useUser

export default Auth
